services:
  - type: web
    name:  mini-project-backend4
    env: docker
    region: oregon  # or your preferred region
    plan: free  # or starter, standard, etc.
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: mini-project-backend4.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: mini-projet-db
          property: connectionString
    
databases:
  - name: mini-projet-db
    plan: free  # or starter
    databaseName:  mini-projet-db
    user: mini_projet_db_user