services:
  - type: web
    name: mini-project-backend9
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /graphql/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "mini-project-backend9.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: mini-projet-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    
databases:
  - name: mini-projet-db
    plan: free
    databaseName: mini-projet-db
    user: mini_projet_db_user